import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Container da imagem de fundo com blur */}
        <div className="background-image-container">
          <img
            src="./images/fundo.jpg"
            alt="Background"
            className="background-image"
          />
        </div>
        {/* Sobreposição para o efeito de blur e legibilidade */}
        <div className="background-overlay"></div>

        {/* Este é o conteúdo real da sua aplicação (páginas, componentes) */}
        {children}
      </body>
    </html>
  );
}
